
default_events:
  
  - create
  - issues
  - pull_request
  - pull_request_review
  - pull_request_review_comment
  - push

default_permissions:
  
   issues: write
   metadata: read
   pull_requests: read
   repository_hooks: read
   statuses: read
